services:
  core:
    build:
      context: ./core/
    ports:
      - 5000:8080
  frontend:
    build:
      context: ./frontend/
    ports:
      - 8080:8080
  mongo:
    build:
      context: ./database/
    command: bash -c "mongod | jq --unbuffered -r '.msg'"
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
# ^ This command is only so mongodb does not spit out disgusting output messages on our docker output. Try it without if you want to see.
# "Entrypoint" allows me to access the "terminal" of insde this container and run commands.

volumes:
  mongodata:
    driver: local
