# Mongo image docker pulls from the official repos ( 7.0 is most recent release )
ARG MONGO_VERSION=7.0
FROM mongo:${MONGO_VERSION}

# Port from container that will be connected (see compose file for localhost accessport)
EXPOSE 27017